export const coffeeDetails=[
    
    {
        id:1,
        name:"Expresso",
        addon:'Milk',
        price:60
    },
    {
        id:2,
        name:"Expresso",
        addon:'Cream',
        price:75
    },
    {
        id:3,
        name:"Expresso",
        addon:'Latte',
        price:100
    },
    {
        id:4,
        name:"Cappuccino",
        addon:'Milk',
        price:80
    },
    {
        id:5,
        name:"Cappuccino",
        addon:'Cream',
        price:90
    },
    {
        id:6,
        name:"Cappuccino",
        addon:'Latte',
        price:125
    },
    {
        id:7,
        name:"Latte",
        addon:'Milk',
        price:100
    },
    {
        id:8,
        name:"Latte",
        addon:'Cream',
        price:125
    },
    {
        id:9,
        name:"Latte",
        addon:'Extra Latte',
        price:150
    },
    
]
export const coffees=[
    {
        id:1,
        name:'Expresso',
    },
    {
        id:2,
        name:'Cappuccino',
    },
    {
        id:3,
        name:'Latte',
    }
]
export const addon=[
    {
        id:1,
        name:'Milk',
    },
    {
        id:2,
        name:'Cream',
    },
    {
        id:3,
        name:'Latte'
    }
]